const PS=(family,model)=>`https://psref.lenovo.com/syspool/Sys/PDF/${family}/${model}/${model}_Spec.pdf`;
const HISTORY='#private-source';
const SOURCES={msi:'https://www.msi.com/Business-Productivity/Modern-14-B5SX/Specification',mac5:'https://support.apple.com/en-ie/126320',mac4:'https://support.apple.com/en-us/122209',zen:'https://www.asus.com/laptops/for-home/zenbook/asus-zenbook-14-oled-um3406/techspec/',zeni:'https://www.asus.com/laptops/for-home/zenbook/asus-zenbook-14-oled-ux3405/techspec/',pro:PS('Yoga','Yoga_Pro_7_14IAH10'),slim:PS('Yoga','Yoga_Slim_7_14ILL10'),slim5:PS('Yoga','Yoga_Slim_7_14ILL11'),idea:PS('IdeaPad','IdeaPad_Slim_5_14AGP11')};
const info={
msi:{model:'B5M · your 16/512 configuration',gpu:'Radeon Vega 8',d:220.2,h:18.1,battery:39,batteryText:'39Wh nominal; your report: 37.802Wh design / 24.852Wh full',tpEstimate:[105,65],touchpad:'Conventional clickpad · material unverified',keyboard:'Backlit; no numpad; dimensions unpublished',material:'Aluminium design (MSI); individual panels unverified',finger:'Not listed',face:'No IR camera listed',charging:'65W barrel; USB-C charging not specified',portsL:['DC','HDMI','USB-C','microSD'],portsR:['USB-A','USB-A','Audio'],portsText:'USB-C 3.2 Gen 2; 2× USB-A; HDMI; microSD; audio; DC',upgrades:'2× DDR4 SODIMM, up to 64GB; 1× M.2 SSD',speakers:'2× 2W',note:'Already owned · no purchase cost',good:'No purchase required; replaceable memory.',bad:'Your worn battery and recorded high drain limit mobility.',bench:[1382,5116],benchSource:'https://browser.geekbench.com/v6/cpu/15707550',benchNote:'Single public Linux Geekbench 6.5 submission; not your unit or a typical-performance claim.',runtime:85/60/.55,runtimeNote:'Your Edge session, extrapolated 100→0; not a controlled test.',runtimeSource:'#private-source',photo:'https://storage-asset.msi.com/global/picture/product/product_1619578455e3ef781d74b6030a47078f47a56080ad.webp'},
mac5:{model:'2026 · 10-core CPU / 8-core GPU',cpu:'Apple M5',gpu:'Apple 8-core GPU',nits:500,battery:53.8,tpEstimate:[128,80],touchpad:'Glass Force Touch · haptic',keyboard:'78 ANSI / 79 ISO keys; backlit; Touch ID',material:'Aluminium enclosure',finger:'Yes · Touch ID',face:'No · camera is not Face ID',charging:'MagSafe 3 / USB-C PD; ≥70W fast charge',portsL:['MagSafe','TB4','TB4'],portsR:['Audio'],portsText:'2× Thunderbolt 4; MagSafe 3; audio. No USB-A / HDMI.',upgrades:'Memory and SSD not user-upgradeable',speakers:'Four-speaker system',note:'Discussed quote · eligibility / stock unverified',good:'Fanless; haptic touchpad; strong short-burst CPU.',bad:'60Hz; fixed RAM/SSD; ARM restrictions for VMs.',bench:[4168,17067],benchSource:'https://www.tomshardware.com/laptops/macbooks/apple-macbook-air-13-inch-m5-review',benchNote:'Geekbench 6: 16GB/1TB, 10-core GPU review unit; your offer has 8-core GPU/512GB.',runtime:15+28/60,runtimeNote:'Tom’s Hardware: web/video/OpenGL, 150 nits; 16GB/1TB, 10-core GPU review unit.',runtimeSource:'https://www.tomshardware.com/laptops/macbooks/apple-macbook-air-13-inch-m5-review'},
zen:{model:'UM3406GA-QD031W',gpu:'Radeon 840M',nits:400,battery:75,tpEstimate:[130,75],touchpad:'Precision clickpad; NumberPad varies by SKU',keyboard:'Backlit chiclet; 1.4mm travel; Copilot',material:'All-metal chassis',finger:'Not listed',face:'Yes · FHD IR Windows Hello',charging:'65W USB-C PD',portsL:['USB-A'],portsR:['HDMI','Audio','USB-C','USB4'],portsText:'USB4 + USB-C 3.2 Gen 2 (PD/display); USB-A; HDMI; audio',upgrades:'32GB soldered; replaceable M.2 SSD',speakers:'Stereo · smart amplifier',note:'eXtra photo 5,299 × 0.90',good:'32GB / 1TB in a light body; OLED; USB-C charging.',bad:'60Hz; soldered memory; modest integrated GPU.',bench:[2615,10557],benchSource:'https://www.ultrabookreview.com/75348-asus-zenbook-14-gorgon-review/',benchNote:'Geekbench 6.6; same CPU/chassis review; power mode matters.',runtime:9,runtimeNote:'8–10h Edge browsing; midpoint 9h, 120 nits, Best Power Efficiency.',runtimeSource:'https://www.ultrabookreview.com/75348-asus-zenbook-14-gorgon-review/',photo:'https://dlcdnwebimgs.asus.com/gain/42476f64-3af2-4f5a-b16d-526bf2a14e33/w800'},
pro:{model:'14IAH10 · 83KF0016AD',gpu:'Intel Arc 140T',nits:500,battery:84,touchpad:'Glass Precision clickpad',keyboard:'6 rows; backlit; 1.5mm travel; Copilot',material:'Aluminium top and bottom',finger:'No',face:'Yes · 5MP IR Windows Hello',charging:'100W USB-C PD',portsL:['HDMI','TB4','TB4'],portsR:['Audio','USB-A','SD'],portsText:'2× Thunderbolt 4; USB-A; HDMI 2.1; SD; audio',upgrades:'32GB soldered; 2× M.2 slots',speakers:'4× 2W · two woofers + two tweeters',note:'eXtra photo 5,759 × 0.90',good:'120Hz OLED touch; glass pad; 32GB; second SSD slot.',bad:'Heavier than Air / Zenbook; soldered memory.',runtimeNote:'Lenovo claims 14.3h PCMark 10 at 120 nits; not a web test.'}
};
for(const l of LAPTOPS)Object.assign(l,info[l.id]);
LAPTOPS.push(
{id:'slim',brand:'Lenovo',name:'Yoga Slim 7 · Ultra 7',model:'14ILL10 · exact Jarir SKU unconfirmed',cpu:'Core Ultra 7 256V',gpu:'Intel Arc 140V',ram:16,ssd:512,price:4399,w:312,d:219.3,h:13.9,weight:1.19,screen:14,res:[1920,1200],hz:60,panel:'OLED',nits:400,color:'#829077',os:'Windows 11',arch:'x86-64',battery:70,tp:[135,80],touchpad:'Glass Precision clickpad',keyboard:'6 rows; backlit; 1.5mm travel',material:'Aluminium top and bottom',finger:'No',face:'Yes · IR Windows Hello',charging:'65W USB-C PD',portsL:['HDMI','TB4','TB4'],portsR:['Audio','microSD','USB-A'],portsText:'2× Thunderbolt 4; HDMI; USB-A; microSD; audio',upgrades:'16GB fixed on-package; 1× M.2 slot',speakers:'Four speakers',note:'Jarir photo · no extra discount',good:'Low weight; glass pad; broad port selection.',bad:'16GB cannot be upgraded; exact screen SKU unconfirmed.'},
{id:'slim5',brand:'Lenovo',name:'Yoga Slim 7 · Ultra 5',model:'14ILL11 · 83R00066AD',cpu:'Core Ultra 5 226V (history; verify SKU)',gpu:'Intel Arc 130V if 226V',ram:16,ssd:1024,price:3734.1,w:312,d:221,h:13.9,weight:1.16,screen:14,res:[1920,1200],hz:60,panel:'OLED',nits:400,color:'#b0a082',os:'Windows 11',arch:'x86-64',battery:70,tp:[135,80],touchpad:'Glass Precision clickpad',keyboard:'6 rows; backlit; 1.5mm travel',material:'Aluminium top and bottom',finger:'No',face:'Yes · IR Windows Hello',charging:'USB-C PD 45–65W',portsL:['USB-C','USB-C'],portsR:['USB-C'],portsText:'3× USB-C 10Gbps (PD / DisplayPort). No USB-A, HDMI or audio.',upgrades:'16GB fixed on-package; replaceable SSD',speakers:'Four speakers',note:'eXtra photo 4,149 × 0.90',good:'Light body; glass touchpad; lower discussed price.',bad:'USB-C-only ports; processor identification is unconfirmed.',provisional:true},
{id:'idea',brand:'Lenovo',name:'IdeaPad Slim 5',model:'14AGP11 · 83S1005DAD',cpu:'Ryzen AI 7 445',gpu:'Radeon 840M',ram:16,ssd:1024,price:3806.1,w:313.4,d:222,h:16.9,weight:1.37,screen:14,res:[1920,1200],hz:60,panel:'OLED',nits:400,color:'#738794',os:'Windows 11',arch:'x86-64',batteryText:'50Wh or 60Wh; exact SKU unconfirmed',tp:[120,75],touchpad:'Mylar (plastic) Precision clickpad',keyboard:'6 rows; backlight depends on SKU',material:'Aluminium top and bottom',finger:'No',face:'Optional IR · verify exact SKU',charging:'USB-C PD; 65W adapter option',portsL:['USB-C','HDMI','USB-C','Audio'],portsR:['microSD','USB-A','USB-A'],portsText:'2× USB-C 10Gbps; 2× USB-A; HDMI; microSD; audio',upgrades:'2× DDR5 SODIMM; AI 7 445 supports 2× M.2 slots',speakers:'2× 2W',note:'eXtra photo 4,229 × 0.90',good:'1TB and upgradeable RAM; OLED at a lower price.',bad:'Plastic touchpad; battery / IR camera depend on SKU.'});
function variant(base,patch){LAPTOPS.push({...LAPTOPS.find(x=>x.id===base),...patch});}
variant('mac5',{id:'mac4',weight:1.24,name:'MacBook Air 13 M4',model:'2025 · 24GB / 512GB',cpu:'Apple M4',gpu:'Apple 10-core GPU',ram:24,price:4999,note:'Older Jarir quote · stock unverified',bench:[3751,14947],benchSource:'https://www.tomsguide.com/computing/macbooks/macbook-air-m4-review',benchNote:'Geekbench 6 review, configuration differs from this 24GB offer.',runtime:null,runtimeNote:'No matched battery result entered.',source:SOURCES.mac4});
variant('zen',{id:'zen16',good:'OLED and a light body at a lower discussed price.',bad:'16GB soldered; offer was unavailable in your earlier discussion.',name:'Zenbook 14 OLED · 16GB',model:'UM3406GA · exact suffix unconfirmed',ram:16,ssd:512,price:3869.1,note:'eXtra photo 4,299 × 0.90 · was out of stock',bench:null,benchNote:'32GB review is not a measurement of this 16GB configuration.',runtime:null,runtimeNote:'No matched independent result entered.',source:SOURCES.zen,upgrades:'16GB soldered; replaceable M.2 SSD'});
variant('zen',{id:'zeni',name:'Zenbook 14 · Ultra 9',model:'UX3405CA-SU855W',cpu:'Core Ultra 9 285H',gpu:'Intel Arc 140T',price:5849.1,res:[2880,1800],hz:120,panel:'OLED touch',weight:1.28,portsR:['HDMI','Audio','TB4','TB4'],portsText:'2× Thunderbolt 4; USB-A; HDMI 2.1; audio',note:'eXtra photo 6,499 × 0.90',good:'32GB; sharp 120Hz OLED; strong CPU benchmark.',bad:'Costs more than Yoga Pro at recovered prices; soldered RAM.',bench:[2938,15689],benchSource:'https://www.91mobiles.com/hub/asus-zenbook-14-ux3405ca-review-core-ultra-power-oled-finesse',benchNote:'Geekbench 6; regional PZ349WS review configuration.',runtime:null,runtimeNote:'No matched battery result entered.',source:SOURCES.zeni,photo:'https://dlcdnwebimgs.asus.com/gain/5d80ba82-0705-4426-a279-5e296df3966f/w800'});
Object.assign(LAPTOPS.find(l=>l.id==='pro'),{portsL:['HDMI','TB4','TB4','SD'],portsR:['USB-A','USB-A','Audio'],portsText:'2× Thunderbolt 4; 2× USB-A; HDMI 2.1; SD; audio',portImage:'assets/pro-ports.jpg'});
Object.assign(LAPTOPS.find(l=>l.id==='slim'),{portsL:['HDMI','TB4','TB4','microSD'],portsR:['USB-A','Audio'],portImage:'assets/slim-ports.jpg'});
Object.assign(LAPTOPS.find(l=>l.id==='slim5'),{portImage:'assets/slim5-ports.jpg'});
Object.assign(LAPTOPS.find(l=>l.id==='idea'),{portsL:['HDMI','USB-C','USB-C','Audio'],portsR:['USB-A','USB-A','microSD'],portImage:'assets/idea-ports.jpg'});
const recovered=[
['flipamd','Lenovo','IdeaPad 5 2-in-1 · AMD','83KT006HAD / 83KT00GHAD conflict','Ryzen AI 7 445 (conflicts with 83KT platform)',16,512,3688.2,'14″ WUXGA touch','eXtra 4,098 × 0.90; 14AKP10 lists AI 300, not 445'],
['flipintel','Lenovo','IdeaPad 5 2-in-1 · Intel','83UG002HAD · 14IPH11','Core Ultra 5 322',16,512,3867.3,'14″ WUXGA IPS touch','eXtra 4,297 × 0.90'],
['yoga7','Lenovo','Yoga 7 2-in-1 · Intel','83TC008JAD','Core Ultra 7 355',16,1024,5669.1,'14″ OLED touch','eXtra 6,299 × 0.90'],
['yoga7amd','Lenovo','Yoga 7 2-in-1 · AMD','Exact SKU not recovered','Ryzen AI 7 445',24,1024,5999,'OLED touch','Jarir photo'],
['slimamd','Lenovo','Yoga Slim 7 · AMD','Exact SKU not recovered','Ryzen AI 7 350',32,1024,6799,'OLED','Jarir photo'],
['hp5','HP','OmniBook 5 · AMD','DT3H2EA','Ryzen AI 7 445',16,512,3959.1,'14″ OLED','eXtra 4,399 × 0.90'],
['hp5i','HP','OmniBook 5 · Intel','Exact SKU not recovered','Core Ultra 5 322',16,512,3899,'Display unverified','Jarir photo'],
['hpaero','HP','OmniBook 7 Aero','Exact SKU not recovered','Ryzen AI 7 350',16,512,5699,'13.3″ 2K IPS','Jarir photo'],
['modern','MSI','Modern 14S AI+','Exact SKU not recovered','Core Ultra 7 355',16,1024,4699,'14″ OLED','Jarir photo'],
['vivoflip','ASUS','Vivobook Flip','Exact SKU not recovered','Core Ultra 7 355',null,null,6199,'Touch; panel unverified','Jarir photo'],
['geek','GEEKOM','GeekBook X14 Pro','185H version unconfirmed','Core Ultra 9 185H',32,null,null,'14″ 2880×1800 OLED 120Hz','No verified Saudi price'],
['vivoold','ASUS','Vivobook 14 · older','Model unknown','Ryzen 5 4500U (uncertain)',8,null,null,'Panel unverified','Historical reference; not a purchase offer'],
['ideapro','Lenovo','IdeaPad Pro 5','Generation/configuration not recovered','Unconfirmed',null,null,null,'Panel unverified','Mentioned in earlier comparisons']
];
for(const [id,brand,name,model,cpu,ram,ssd,price,panel,note] of recovered)LAPTOPS.push({id,brand,name,model,cpu,ram,ssd,price,panel,note,os:'Windows · edition unverified',arch:'x86-64',provisional:true,good:'Additional comparison candidate.',bad:'Exact configuration and physical design need verification.',source:HISTORY});
for(const l of LAPTOPS){l.source ||= SOURCES[l.id]||HISTORY;l.priceSource=HISTORY;l.status=l.provisional?'Needs SKU verification':'Platform researched';}
const HISTORY_SOURCES=[];
