// First-hand community reports checked 7 October 2026. Scores are unchanged.
OWNER_REPORTS.zeni.push(
  {title:'Reddit: 285H/32GB owner on Debian',kind:'Owner · matching CPU/RAM, different OS',config:'Zenbook UX3405CA · Core Ultra 9 285H · 32GB · Debian Linux',result:'About 8–10 hours of light browsing; slightly longer with local video. Another owner of the same model reports more than 8 hours of browsing and coding on Ubuntu power saver.',conditions:'Linux and light use; no matched Windows discharge test.',notes:'The Windows battery estimate in the comparison stays based on its separate hands-on review.',url:'https://www.reddit.com/r/ASUS/comments/1twg0h3/asus_zenbook14_ux3405caultra_7_255h16gb_ram1tb/'},
  {title:'Reddit: 285H/32GB owner follow-up',kind:'Owner · matching CPU/RAM',config:'Zenbook UX3405CA · Core Ultra 9 285H · 32GB; regional screen/SSD unspecified',result:'Likes the screen and build, but finds the glossy surface reflective and the case prone to fingerprints. Wi-Fi range was weak on this owner’s unit; heavy loads made it hot.',conditions:'Personal use over several months; no timed battery result.',notes:'One device experience; no general reliability or speaker score inferred.',url:'https://www.reddit.com/r/ASUS/comments/1kdn2xq/concerns_about_zenbook_14_ux3405ca/'}
);
OWNER_REPORTS.honor=[{title:'Reddit: Art 14 2025 owners discuss daily use',kind:'Owners · same generation, regional variants',config:'MagicBook Art 14 2025; processor/RAM unspecified',result:'One 2024/2025 owner finds the newer screen less reflective and keyboard lighting improved. Another 2025 owner praises the screen, keyboard and touchpad, but could not get the touchpad working in Kubuntu.',conditions:'China and UK units; the touchpad issue concerns Linux.',notes:'The comments do not verify the shortlisted 255H/32GB configuration.',url:'https://www.reddit.com/r/linuxhardware/comments/1m3zfiy/linux_support_of_honor_magicbook_art_14_and_honor/'}];
OWNER_REPORTS.hpx=[{title:'Reddit: OmniBook Ultra owner on Arch Linux',kind:'Owner · HX 375 discussion; CPU suffix unconfirmed',config:'OmniBook Ultra 14 from an HX 375 thread; commenter did not restate CPU/RAM',result:'After about seven hours of Google Docs, Sheets and browsing, the owner reports around 60% charge remaining. They find it cool and quiet on Arch Linux.',conditions:'Arch Linux; Windows battery life untested. The claimed 15-hour total is an estimate.',notes:'Not a measured full discharge or a direct test of the Saudi Windows offer.',url:'https://www.reddit.com/r/AMDLaptops/comments/1hetfj6/hp_omnibook_ultra_14_ryzen_ai_9_hx_375_and/'}];
OWNER_REPORTS.slimamd=[{title:'Reddit: 14AKP10 ownership report',kind:'Owner · matching chassis and Ryzen AI 7 350',config:'Yoga Slim 7 14AKP10 · Ryzen AI 7 350 · Fedora 42; RAM/SSD unspecified',result:'Keyboard backlight, touch and function keys worked. The owner needed audio tweaks and reported crashes on sleep. Another owner reported unstable Realtek Wi-Fi in Linux live sessions, while the original owner did not.',conditions:'Linux setup; wireless hardware varies. No Windows battery test.',notes:'This is the Slim 7 14AKP10, not the Yoga 7 2-in-1 or Intel Slim 7.',url:'https://www.reddit.com/r/Fedora/comments/1n22vja/ownership_report_of_lenovo_yoga_slim_7_14akp10/'}];
OWNER_REPORTS.tecno=[{title:'Epey: MegaBook S14 owner after a month',kind:'Owner · same S14 family, different CPU/RAM',config:'MegaBook S14 · Core Ultra 5 125H · 16GB / 1TB; not the Saudi 155H/32GB offer',result:'Owner likes the light body and vivid OLED, says Adobe apps run comfortably, and reports 4–5 hours in ordinary use. The right USB-C is data only.',conditions:'Self-reported use; brightness, workload and charge endpoints unspecified.',notes:'The 125H/16GB report does not set runtime for the shortlisted 155H/32GB.',url:'https://www.epey.com/laptop/tecno-megabook-s14.html'}];
OWNER_REPORTS.mac24=[{title:'Reddit: first impressions of the 24GB M5 Air',kind:'Owner · matching memory/storage; size unconfirmed',config:'MacBook Air M5 · 24GB / 512GB; screen size not stated',result:'Four hours of YouTube left the owner at 78% charge. They like the cool, quiet use, keyboard and trackpad, while noting limited ports and fixed storage.',conditions:'Two days of ownership; video playback only. Starting charge and brightness unstated.',notes:'A short observation, not a full battery test or a reason to change the scored runtime.',url:'https://www.reddit.com/r/macbookair/comments/1v00rb7/purchased_my_first_ever_mac/'}];
OWNER_REPORTS.msi=[
  {title:'Reddit: Modern 14 B5M study use',kind:'Owner · matching B5M family',config:'Modern 14 B5M; exact CPU/RAM unspecified',result:'Owner found it portable and comfortable for classes and study during early ownership.',conditions:'Brief first impression; no timed battery test.',notes:'Your own B5M and battery session remain the most relevant reference for your unit.',url:'https://www.reddit.com/r/MSILaptops/comments/16brqy4'},
  {title:'Reddit: B5M owners compare battery use',kind:'Owners · matching B5M family, mixed batteries',config:'Modern 14 B5M; commenters describe different memory and roughly 38–39Wh batteries',result:'One owner reported 4–5 hours between 77% and 17% charge with an hour of camera use. Another reported five hours from 100% to 10% while browsing, coding and playing YouTube music.',conditions:'Different units and workloads; neither is your 5700U configuration.',notes:'Context only; not substituted for your measured baseline.',url:'https://www.reddit.com/r/MSILaptops/comments/sx1gqt'}
];
REVIEW_SEARCH_NOTES.zeni='Two 285H/32GB owner threads add screen, Wi-Fi, heat and Linux battery impressions.';
REVIEW_SEARCH_NOTES.honor='First-hand reports cover the 2025 Art 14 chassis, but not a confirmed 255H/32GB unit.';
REVIEW_SEARCH_NOTES.hpx='An OmniBook Ultra owner posted in an HX 375 thread; exact CPU/RAM unconfirmed and Linux was used.';
REVIEW_SEARCH_NOTES.slimamd='An owner of the Ryzen AI 7 350 14AKP10 reports Linux compatibility; Windows runtime remains unverified.';
REVIEW_SEARCH_NOTES.tecno='A month-long S14 owner report uses 125H/16GB. No confirmed 155H/32GB owner report found.';
REVIEW_SEARCH_NOTES.mac24='A 24GB/512GB M5 Air owner describes video playback and first impressions; screen size is unstated.';
REVIEW_SEARCH_NOTES.slim5='Buying discussions exist for 14ILL11, but no owner report confirmed to this configuration.';
REVIEW_SEARCH_NOTES.msi='Your own battery recording is the best baseline for your B5M. Other B5M posts are context only.';
