// Research checked 19 Sep 2026. Reports are observations, not a representative survey.
const OWNER_REPORTS={
pro:[
{title:'Two-month owner review',kind:'Owner · matching 255H CPU',config:'Yoga Pro 7i Aura · Ultra 7 255H; RAM/SSD unspecified',result:'Windows: approximately 8–9h. Linux: approximately 6–8h.',conditions:'Brightness, charge endpoints and exact workload during runtime observations are not stated. Owner uses VMs, containers and heavy multitasking. A commenter reports only 4–5h with Chrome and Claude; their exact configuration is unverified.',notes:'Owner likes keyboard, touchpad and speakers; mentions minor creaks and Linux audio / Wi-Fi resume issues. These reports do not establish failure rates. Scoring uses 8.5h, the midpoint of this one Windows report, not an average across owners.',url:'https://www.reddit.com/r/linuxhardware/comments/1ogn76g/yoga_pro_7i_aura_edition_ultra_7_255h_short/'},
{title:'Rolling owner review',kind:'Owner · matching 255H CPU',config:'Yoga Pro 7i Aura Gen 10 · Fedora 43 KDE',result:'5–6h observed from 80% to 25%. Full-charge extrapolation: 9.1–10.9h.',conditions:'Mixed use, battery saver, 40–50% brightness. Calculation: observed hours ÷ 0.55; not a full-discharge measurement. Heavy computation: 25% in 45 minutes, approximately 3h extrapolated.',notes:'Later Windows comments report roughly 8–10W browsing; media playback increases drain. Reports Linux audio/resume issues and deck vibration at high speaker volume. Power-mode observations are not controlled cross-OS tests.',url:'https://www.reddit.com/r/UnboxParadigm/comments/1ozdklg/rolling_review_of_yoga_pro_7i_aura_gen_10_core/'},
{title:'Notebookcheck controlled review',kind:'Lab · different CPU',config:'Yoga Pro 7 14IAH10 · Ultra 9 285H · 32GB / 1TB · 3K OLED · 84Wh',result:'Wi-Fi: 10h 16m at 150 nits; 5h 43m at maximum brightness. Geekbench 6.7: 2,863 / 17,846.',conditions:'Related chassis and display; Ultra 9 test results are not measurements of the shortlisted Ultra 7.',notes:'Retained for context only. Not substituted into the Ultra 7 CPU or battery score.',url:'https://www.notebookcheck.net/Lenovo-Yoga-Pro-7i-Gen-10-Aura-Edition-review-Multimedia-laptop-with-a-great-OLED-touchscreen.1158702.0.html'}],
zen:[
{title:'UnGeek hands-on review',kind:'Small review · same CPU, different memory',config:'UM3406GA · Ryzen AI 7 445 · 16GB / 1TB · WUXGA 60Hz · 75Wh',result:'An eight-hour workday with charge remaining. A 2.5h movie consumed 13% (100% → 87%).',conditions:'Movie at 50% brightness and volume. Workday workload/endpoints not fully specified. Short movie sample is not treated as a full battery benchmark.',notes:'Supports everyday endurance, but differs from the shortlisted 32GB configuration. No movie extrapolation is used in the score.',url:'https://www.ungeek.ph/2026/03/asus-zenbook-14-2026-um3406ga-review-geek-lifestyle/'},
{title:'Fossbytes daily-driver review',kind:'Small review · different CPU',config:'UM3406GA · Ryzen AI 5 430 · 16GB / 512GB · FHD+ OLED touch',result:'Reviewer reports approximately 12h screen-on time with Chrome, spreadsheets and YouTube.',conditions:'Brightness and charge endpoints unspecified; two weeks of personal use.',notes:'Same UM3406GA name, different processor. Context only; not transferred to Ryzen AI 7 445 scoring.',url:'https://fossbytes.com/asus-zenbook-14-2026-review/'}],
mac5:[
{title:'Study and browsing owner report',kind:'Owner · base 13-inch M5',config:'MacBook Air M5 13-inch base model · macOS Tahoe',result:'Approximately 7h screen time using 55% battery. Linear full-charge estimate: 12.7h.',conditions:'Studying and browsing; owner switched Firefox to Safari. Brightness unspecified. New device; not a controlled full discharge.',notes:'Calculation: 7 ÷ 0.55. Shown alongside the existing lab result, not substituted for it.',url:'https://www.reddit.com/r/macbookair/comments/1vs7blp/m5_13_macbook_air_battery_life_is_7_hours_for_55/'},
{title:'Contrasting new-device battery complaint',kind:'Owner · matching 16GB / 512GB',config:'13-inch M5 · 10-core CPU / 8-core GPU · four-day-old device',result:'2h 43m elapsed; Activity Monitor estimated 3h 37m remaining.',conditions:'Mostly Safari, Mail and Messages. Remaining time is an OS prediction, not measured runtime; background setup activity not established.',notes:'Do not interpret the post’s claimed 5.5h as a full-discharge test. Even adding the reported values yields 6h 20m of elapsed plus predicted time, not a measured total.',url:'https://www.reddit.com/r/macbookair/comments/1s83yp8/m5_macbook_air_getting_terrible_battery_life/'}],
slim:[{title:'Owner compares Intel and AMD Slim 7',kind:'Owner · related configurations',config:'Yoga Slim 7 Gen 10 · Intel 258V vs Ryzen AI 7 350; not shortlisted 256V',result:'Owner preferred Intel unplugged responsiveness and quietness. No completed battery cycle reported.',conditions:'Two browsers with 20–30 tabs each, messaging, spreadsheets and background apps. Early personal impressions, not a benchmark.',notes:'Reports AMD backplate creaks and Intel touchpad rattle; later returned both. No population-wide reliability conclusion or battery score inferred. A 15ILL9 15-inch review was not mapped to this 14ILL10.',url:'https://www.reddit.com/r/laptops/comments/1kzdamy/impression_ama_core_ultra_7_258v_vs_ryzen_7_ai/'}]
};
OWNER_REPORTS.zen16=OWNER_REPORTS.zen;OWNER_REPORTS.slimamd=OWNER_REPORTS.slim;
OWNER_REPORTS.zeni=[{title:'Ultrabookreview longer-term test',kind:'Hands-on review · matching core configuration',config:'UX3405CA · Ultra 9 285H · 32GB / 1TB · 2.8K 120Hz OLED · 75Wh',result:'Edge browsing: approximately 7–9h. Google Drive text editing and YouTube: approximately 10–11h. Gaming: approximately 2h.',conditions:'Around 120 nits, 120Hz, Windows Best Power Efficiency, Standard mode, Wi-Fi on, BIOS 307. Published ranges accompany observed power draw; full-discharge timing is not established.',notes:'BIOS changes affected light-use endurance. Battery score uses 8h, midpoint of the browsing range. Regional SKU may differ; lower-resolution 60Hz results are not substituted.',url:'https://www.ultrabookreview.com/71699-asus-zenbook-14-2025-intel-review/'}];
OWNER_REPORTS.mac4=[{title:'Developer’s one-year M4 Air review',kind:'Personal blog · 24GB M4',config:'MacBook Air M4 · 24GB; screen size and SSD not specified',result:'Owner reports comfortable day-to-day development and sufficient memory for their Linux VM / container workflow. No numeric battery test.',conditions:'Neovim/LSP, Go compilation and container-image builds; occasional media conversion and local model inference.',notes:'Good subjective evidence for this user’s workflow, not a measured performance comparison or a basis for filling battery hours. Heavy inference/media work made the chassis hot.',url:'https://notnotp.com/notes/macbook-air-m4-for-dev/'}];
Object.assign(LAPTOPS.find(l=>l.id==='zeni'),{runtime:8,runtimeSource:OWNER_REPORTS.zeni[0].url,runtimeNote:'Ultrabookreview: midpoint of 7–9h Edge browsing range, 120 nits / 120Hz, Best Power Efficiency, Standard mode, BIOS 307; 285H / 32GB / 1TB / 2.8K panel. Range reported alongside power draw, not confirmed full-discharge timing.'});
const REVIEW_SEARCH_NOTES={pro:'Searched Yoga Pro 7, Pro 7i, Aura Gen 10, 14IAH10 and 255H. Pro, Slim, Yoga Book and 2-in-1 are different families.',zen:'Searched UM3406GA and Zenbook 14 Ryzen AI 7 445. Matched small reviews found; Reddit results were mainly buying questions. GA alone does not identify CPU.',zen16:'Related 16GB/1TB review found; your historical offer was 16GB/512GB.',slim:'Searched Yoga Slim 7 / 7i Aura, 14ILL10 and 256V. No sufficiently specified matching owner runtime found. 258V observations remain related-configuration evidence.',idea:'Searched IdeaPad Slim 5, Slim 5a Gen 11, 14AGP11 and AI 7 445. Located buying discussions and 16-inch posts, but no sufficiently specified 14-inch owner runtime. Pro 5 and 2-in-1 results are not interchangeable.',msi:'Your recovered Edge session remains the most relevant personal baseline; 24.852Wh full-charge capacity and 85% → 30% over 85 minutes. See Your battery baseline.',mac5:'Searched M5 MacBook Air 13-inch owner battery reports; kept contrasting observations and distinguished OS predictions from measured usage.'};
Object.assign(LAPTOPS.find(l=>l.id==='pro'),{bench:[2690,15057],benchSource:'https://nanoreview.net/en/laptop/lenovo-yoga-pro-7i-aura-edition-14-gen-10?m=r%7e32.s%7e1024',benchNote:'NanoReview-reported Geekbench 6 reference: 2,690 / 15,057 on the base page. Linked selection is 32GB/1TB; selected-page results and test-unit provenance could not be independently verified. Not the Ultra 9 Notebookcheck score.',runtime:8.5,runtimeSource:OWNER_REPORTS.pro[0].url,runtimeNote:'PROVISIONAL owner reference: midpoint of reported Windows 8–9h on 255H. Brightness / endpoints unspecified; another commenter reports 4–5h. Not a lab test or a guaranteed range.',runtimeCaution:true});
function renderOwnerReports(){return `<div class="detail-body"><div class="eyebrow">REAL-WORLD EVIDENCE · CHECKED 19 SEP 2026</div><h3>What people actually experienced</h3><p>Match the full model, processor, screen and OS before comparing. Owner reports are self-reported and not a representative sample. Partial-charge extrapolations assume constant drain. Different tests are not averaged together.</p>${current().map(l=>`<section class="source-card"><h3>${esc(l.name)}</h3><p class="note">${esc(REVIEW_SEARCH_NOTES[l.id]||((OWNER_REPORTS[l.id]||[]).length?'Review configuration and limitations are stated below.':'No matched owner test added in this research pass. Missing evidence is not a negative review.'))}</p>${(OWNER_REPORTS[l.id]||[]).map(r=>`<article class="owner-report"><span class="tag">${esc(r.kind)}</span><h4>${link(r.url,r.title)}</h4><p><b>Tested:</b> ${esc(r.config)}</p><p><b>Observed:</b> ${esc(r.result)}</p><p><b>Conditions:</b> ${esc(r.conditions)}</p><p class="note">${esc(r.notes)}</p></article>`).join('')}</section>`).join('')}</div>`;}


// User-supplied review photos, 20 September 2026. Supersedes earlier Zenbook test sources.
const ZEN_PHOTO_REPORTS=[
{title:'YouTube playback test — result photo',kind:'Review photographed by user · matching CPU',config:'Zenbook 14 · Ryzen AI 7 445, identified by user; exact RAM, SSD and SKU not visible',result:'16h 42m YouTube playback (16.7 hours).',conditions:'80% display brightness, 60Hz, keyboard backlight OFF. OS, power mode, video resolution and charge endpoints not visible in the supplied frames.',notes:'Playback endurance is not browsing or mixed-use endurance. Battery reference uses this reported duration; configuration and endpoint uncertainty remain.',url:'assets/zen445-tests/34.jpg'},
{title:'Minecraft battery test — result photo',kind:'Review photographed by user',config:'Same user-identified Zenbook 14 Ryzen AI 7 445 review',result:'6h 27m Minecraft (6.45 hours).',conditions:'80% display brightness, 60Hz, keyboard backlight OFF. Game version, settings, FPS cap and charge endpoints are not shown.',notes:'Kept as a separate gaming workload; not averaged with playback.',url:'assets/zen445-tests/23.jpg'},
{title:'Cinebench R23 — result photo',kind:'Review photographed by user',config:'Same user-identified Zenbook 14 Ryzen AI 7 445 review',result:'Single-core 1,811; multi-core 11,021.',conditions:'Power mode, plugged-in status and test duration are not shown.',notes:'Cinebench R23 is separate from Geekbench 6. No conversion or substitution into the Geekbench-based CPU ranking.',url:'assets/zen445-tests/17.jpg'},
{title:'3DMark Time Spy — result photo',kind:'Review photographed by user',config:'Same user-identified Zenbook 14 Ryzen AI 7 445 review',result:'Graphics score 1,784.',conditions:'Power mode and plugged-in status are not shown.',notes:'Graphics subscore, not the overall Time Spy score. Not combined with Metal or other GPU tests.',url:'assets/zen445-tests/14.jpg'},
{title:'Idle power — review claim',kind:'Review photographed by user',config:'Slide labels Ryzen 7 445; user identifies Ryzen AI 7 445',result:'3–5W idle reported.',conditions:'Measurement scope is not shown (CPU/APU versus complete system).',notes:'The separate telemetry photo is cropped and does not establish sensor scope. No whole-system battery calculation inferred.',url:'assets/zen445-tests/31.jpg'},
{title:'Internal layout — review photo',kind:'Review photographed by user',config:'User-identified Zenbook 14 Ryzen AI 7 445',result:'Soldered RAM; one M.2 SSD slot; soldered Wi-Fi.',conditions:'Visible teardown slide labels; exact SSD form factor and RAM capacity are not established.',notes:'Additional supplied frames show playback conditions (38.jpg), gaming conditions (26.jpg) and cropped telemetry (29.jpg).',url:'assets/zen445-tests/20.jpg'}
];
OWNER_REPORTS.zen=ZEN_PHOTO_REPORTS;
OWNER_REPORTS.zen16=ZEN_PHOTO_REPORTS;
REVIEW_SEARCH_NOTES.zen='The supplied photos provide Cinebench R23, Time Spy and battery results. The existing Geekbench 6 review reference is retained separately in Benchmarks. Photo-review URL and exact tested RAM/SSD configuration were not supplied.';
REVIEW_SEARCH_NOTES.zen16='Related Ryzen AI 7 445 evidence only: photos do not confirm this 16GB/512GB configuration, so its scores remain unfilled.';
Object.assign(LAPTOPS.find(l=>l.id==='zen'),{bench:[2615,10557],benchSource:'https://www.ultrabookreview.com/75348-asus-zenbook-14-gorgon-review/',benchNote:'Geekbench 6.6: 2,615 single / 10,557 multi; existing same-CPU/chassis review reference retained. Separate photo-supplied Cinebench R23 results below; never mixed with Geekbench.',r23:[1811,11021],timeSpyGraphics:1784,runtime:16.7,runtimeSource:'assets/zen445-tests/34.jpg',runtimeNote:'YouTube playback: 16h 42m; 80% brightness, 60Hz, keyboard backlight off. Exact RAM/SSD, OS, power mode and charge endpoints not visible. Not a mixed-use result.',runtimeCaution:true,upgrades:'Soldered RAM; 1× M.2 SSD slot; soldered Wi-Fi (supplied teardown photo)',idleNote:'3–5W reported idle; sensor scope unspecified',gamingRuntime:'6h 27m Minecraft; 80% brightness, 60Hz, keyboard backlight off; game settings and endpoints unspecified'});

// User-shared discussion: related configuration; no benchmark substitution.
OWNER_REPORTS.zen.push({title:'Reddit: Ryzen AI 7 350 owner in a buying discussion',kind:'Owner comment · different CPU',config:'Commenter owns a Zenbook 14 Ryzen AI 7 350 with 32GB RAM; exact SKU and screen unspecified',result:'Previously owned a 2021 Zenbook that still worked, with degraded battery life and 8GB RAM. No timed battery test or measured benchmark provided.',conditions:'Buying advice thread comparing MacBook Air M4, Zenbook and MacBook Neo. Performance comparisons link to third-party aggregate sites rather than the commenter’s own tests.',notes:'Claims about the 445 being slower and the 285H running hot are not direct measurements of those models. Broad claims that all ASUS devices are defective are unsupported and excluded. Context only; Geekbench, R23 and battery scoring remain unchanged.',url:'https://www.reddit.com/r/laptops/comments/1tuqbtt/macbook_air_v_asus_zenbook_14_ryzen_7_v_macbook/'});

const M5_ZEN_STEM_DISCUSSION={"title":"Reddit: M5 Air versus Zenbook 14 for a STEM student","kind":"Buying discussion · mixed models, no controlled comparison","config":"Original shortlist: M5 Air 16GB/512GB versus Zenbook 14 Ryzen AI 7 350, 16GB/1TB; not the Ryzen AI 7 445","result":"An S14 owner likes its display and gaming experience, but that is a different Zenbook family. A Mac owner reports over 10h from a four-year-old M1; this is not an M5 runtime measurement.","conditions":"No matched head-to-head benchmark, brightness settings or battery endpoints. Prices are historical Canadian offers, not Saudi availability. Participants also discuss M3, A14 and other unrelated models.","notes":"Useful questions: required STEM software, specific game compatibility, storage needs and sustained workloads. Display, sound, reliability and lifespan claims are opinions without comparable measurements. No changes to CPU, battery or sound scores.","url":"https://www.reddit.com/r/laptops/comments/1vcajag/macbook_m5_vs_asus_zenbook_14/"};
OWNER_REPORTS.zen.push(M5_ZEN_STEM_DISCUSSION);
OWNER_REPORTS.mac5.push(M5_ZEN_STEM_DISCUSSION);
